#!/usr/bin/env node
/**
 * Pulls the Notion database into data/places.notion.json.
 *
 *   NOTION_KEY=secret_... node scripts/sync-notion.mjs [--force]
 *
 * Writes nothing but that snapshot; scripts/build-page.mjs turns it into the page.
 * Refuses to shrink the map by more than SHRINK_LIMIT in one go — a partial response or a
 * half-broken integration must not quietly delete most of the pins on a live site.
 * --force overrides that check.
 */
import { appendFileSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "data/places.notion.json");

const DATABASE_ID = "5cc1a3b3-dcac-4ddf-b86c-01e6732db5e7";
const NOTION_VERSION = "2022-06-28";
const SHRINK_LIMIT = 0.2; // refuse a sync that drops >20% of rows
const PAGE_SIZE = 100;

const KEY = process.env.NOTION_KEY;
if (!KEY) {
  console.error("NOTION_KEY is not set.");
  console.error("Locally: NOTION_KEY=secret_... node scripts/sync-notion.mjs");
  console.error("In CI: add it under Settings > Secrets and variables > Actions.");
  process.exit(1);
}

/* ---------- Notion property readers (the API nests everything by type) ---------- */
const title = (p) => (p?.title || []).map((t) => t.plain_text).join("").trim() || null;
const text = (p) => (p?.rich_text || []).map((t) => t.plain_text).join("").trim() || null;
const select = (p) => p?.select?.name ?? null;
const multi = (p) => (p?.multi_select || []).map((o) => o.name);
const number = (p) => (typeof p?.number === "number" ? p.number : null);

function toRow(page) {
  const p = page.properties || {};
  return {
    id: page.id.replace(/-/g, ""),
    name: title(p["Name"]) || "(untitled)",
    city: select(p["City"]) || "",
    neighborhoods: multi(p["Neighborhood"]),
    type: select(p["Type"]) || "",
    signature: text(p["Signature"]),
    hours: text(p["Hours"]),
    reservation: select(p["Reservation"]),
    address: text(p["Address / Station"]),
    lat: number(p["Latitude"]),
    lng: number(p["Longitude"]),
    createdTime: page.created_time || null,
  };
}

async function queryAll() {
  const rows = [];
  let cursor;
  for (let guard = 0; guard < 50; guard++) {
    const res = await fetch(`https://api.notion.com/v1/databases/${DATABASE_ID}/query`, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${KEY}`,
        "Notion-Version": NOTION_VERSION,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ page_size: PAGE_SIZE, ...(cursor ? { start_cursor: cursor } : {}) }),
    });

    if (!res.ok) {
      const body = await res.text().catch(() => "");
      if (res.status === 404) {
        throw new Error(
          `Notion returned 404 for the database.\n` +
            `This almost always means the integration hasn't been given access:\n` +
            `open the database in Notion, ••• menu > Connections, and add it.\n${body}`,
        );
      }
      if (res.status === 401) throw new Error(`Notion rejected NOTION_KEY (401).\n${body}`);
      throw new Error(`Notion ${res.status}: ${body}`);
    }

    const json = await res.json();
    rows.push(...json.results.map(toRow));
    if (!json.has_more) return rows;
    cursor = json.next_cursor;
  }
  throw new Error("Notion pagination did not terminate after 50 pages.");
}

function previousCount() {
  try {
    return JSON.parse(readFileSync(OUT, "utf8")).rows.length;
  } catch {
    return 0; // first run
  }
}

/** Stable field order and one row per line, so the committed diff reads like a changelog. */
function serialise(rows) {
  const ORDER = ["id", "name", "city", "neighborhoods", "type", "signature", "hours", "reservation", "address", "lat", "lng", "createdTime"];
  const body = rows
    .map((r) => {
      const o = {};
      for (const k of ORDER) o[k] = r[k] ?? null;
      return JSON.stringify(o);
    })
    .join(",\n");
  return [
    "{",
    '  "_comment": "GENERATED by scripts/sync-notion.mjs from Notion. Do not edit by hand; edit the Notion database instead.",',
    `  "database": ${JSON.stringify(DATABASE_ID)},`,
    `  "syncedAt": ${JSON.stringify(new Date().toISOString())},`,
    '  "rows": [',
    body,
    "  ]",
    "}",
    "",
  ].join("\n");
}

const summary = [];
const line = (s) => { summary.push(s); console.log(s); };

const rows = await queryAll();
rows.sort((a, b) => a.city.localeCompare(b.city) || a.name.localeCompare(b.name));

const before = previousCount();
const shrink = before ? (before - rows.length) / before : 0;
line(`fetched ${rows.length} rows (previously ${before})`);
for (const city of [...new Set(rows.map((r) => r.city))].sort()) {
  line(`  ${city}: ${rows.filter((r) => r.city === city).length}`);
}
const missing = rows.filter((r) => r.lat == null || r.lng == null);
if (missing.length) line(`no coordinates, will not be pinned: ${missing.map((r) => r.name).join(" | ")}`);
const noCity = rows.filter((r) => !r.city);
if (noCity.length) line(`no City set, will not render: ${noCity.map((r) => r.name).join(" | ")}`);

if (shrink > SHRINK_LIMIT && !process.argv.includes("--force")) {
  console.error(
    `\nRefusing to write: row count fell ${(shrink * 100).toFixed(0)}% (${before} -> ${rows.length}), ` +
      `over the ${SHRINK_LIMIT * 100}% limit.\n` +
      `If the rows really were deleted in Notion, re-run with --force ` +
      `(or the workflow's "force" input).`,
  );
  process.exit(1);
}

// Compare ignoring syncedAt, so an unchanged database produces no commit.
const stripStamp = (s) => s.replace(/^\s*"syncedAt".*$/m, "");
const next = serialise(rows);
let changed = true;
try {
  changed = stripStamp(readFileSync(OUT, "utf8")) !== stripStamp(next);
} catch { /* no previous file */ }

if (changed) {
  writeFileSync(OUT, next);
  line("data/places.notion.json updated.");
} else {
  line("no changes since the last sync.");
}

if (process.env.GITHUB_STEP_SUMMARY) {
  appendFileSync(process.env.GITHUB_STEP_SUMMARY, `### Notion sync\n\n\`\`\`\n${summary.join("\n")}\n\`\`\`\n`);
}
