#!/usr/bin/env node
/* Rebuild src/data/icons.js from the Streamline set.

     npm i && node tools/fetch-icons.mjs

   The page used to label everything with emoji, which are somebody else's artwork:
   the same category is a different drawing on Android, on iOS and on a Samsung
   phone, and half of them are pictures of American food. These are Streamline
   Regular instead — one grid, one stroke weight, and the same drawing everywhere.

   The icons are vendored the way Leaflet and the fonts are: nothing is fetched at
   runtime, and only the two dozen used here are copied out of the 3,900 in the
   package. STREAMLINE below is the whole map from a name this page uses to a name
   in the set; change one there and re-run this, rather than editing the generated
   file by hand.

   Two rules the set itself enforces, and this script keeps: only the plain weight
   (a `-solid` or `-remix` sibling is a different drawing at a different weight),
   and only icons on the set's own 14x14 grid, so one stroke width reads the same
   at every size on the page. */

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { createRequire } from "node:module";
import { ROOT } from "./lib.mjs";

const require = createRequire(import.meta.url);
let SET, INFO;
try {
  SET = require("@iconify-json/streamline/icons.json");
  INFO = require("@iconify-json/streamline/info.json");
} catch { console.error("@iconify-json/streamline is not installed — run npm i first"); process.exit(1); }

/* page name -> Streamline name. The long names are the set's own; they read as a
   sentence of keywords because that is how Streamline ships them. */
const STREAMLINE = {
  // the nine categories, in CAT_ORDER
  hotel:    "hotel-bed-2",
  food:     "pork-meat",
  cafe:     "coffee-mug",
  bakery:   "food-baguette-cook-bread-gluten-drink-cooking-nutrition-baguette-food",
  dessert:  "cake-slice",
  bar:      "cocktail",
  shopping: "shopping-bag-hand-bag-2",
  landmark: "travel-places-column-1-pillar-building-historical-column",
  beauty:   "lipstick",

  // the header's four toggles
  rail:     "high-speed-train-front",
  me:       "location-target-1",
  offline:  "download-box-1",
  day:      "brightness-1",
  night:    "waning-cresent-moon",

  // the two view switches and the two side tabs
  map:      "map-fold",
  list:     "bullet-list",
  plan:     "blank-calendar",

  // the controls
  add:      "add-1",
  check:    "check",
  close:    "delete-1",
  drag:     "arrow-move",

  // the small ones inside a row
  pin:      "location-pin-3",
  walk:     "arrow-roadmap",
  next:     "interface-arrows-right-arrow-right-keyboard",
  out:      "interface-arrows-diagonal-1-expand-smaller-retract-bigger-big-small-diagonal",
};

const missing = [], offGrid = [];
const out = {};
for (const [key, name] of Object.entries(STREAMLINE)){
  const ic = SET.icons[name];
  if (!ic){ missing.push(`${key} -> ${name}`); continue; }
  if (ic.width || ic.height) offGrid.push(`${key} -> ${name} (${ic.width || SET.width}x${ic.height || SET.height})`);
  out[key] = ic.body;
}
if (missing.length){ console.error("not in the set:\n  " + missing.join("\n  ")); process.exit(1); }
if (offGrid.length){ console.error(`not on the ${SET.width}x${SET.height} grid:\n  ` + offGrid.join("\n  ")); process.exit(1); }

const license = INFO.license;
const lines = [
  "/* GENERATED by tools/fetch-icons.mjs — do not edit by hand.",
  "",
  `   ${Object.keys(out).length} icons from Streamline (${INFO.total} in the set), drawn on a`,
  `   ${SET.width}x${SET.height} grid in the regular weight, stroked in currentColor so every one of`,
  "   them takes the colour of whatever it sits in.",
  "",
  `   Streamline, ${license.title} (${license.url}) — ${INFO.author.url}`,
  "",
  "   Add or change one in the STREAMLINE table in tools/fetch-icons.mjs and re-run it. */",
  "",
  `export const ICON_BOX = ${SET.width};`,
  "",
  "/* The Streamline name each of these came from, so a swap can be traced back:",
  ...Object.entries(STREAMLINE).map(([k, n]) => `     ${k.padEnd(9)} ${n}`),
  " */",
  "export const ICONS = {",
  ...Object.entries(out).map(([k, body]) => `  ${k}: ${JSON.stringify(body)},`),
  "};",
  "",
];
writeFileSync(join(ROOT, "src/data/icons.js"), lines.join("\n"));
console.log(`wrote src/data/icons.js — ${Object.keys(out).length} icons on a ${SET.width}x${SET.height} grid`);
